### ISSUE TITLE
Error when used in winforms app

### ISSUE THREAD

**Issue by Ranodj** [asc-community/AngouriMath#315] opened 2021-01-05 16:48 UTC
When I try to use this library in a winforms app I get an error telling me that it doesn't have a strong name. What is a strong name, and how do I give it one?

**Comment by WhiteBlackGoose** [comment] 2021-01-05 17:21
This is weird. It may appear if you're trying to  add some project as a dependency to AngouriMath. But you're likely to set it as a Nuget package, right?

**Comment by WhiteBlackGoose** [comment] 2021-01-27 06:25
Seems like 1.2.0-preview.5 should be on FieldCache 1.0.0-alpha.3. That's my mistake, I'll fix as soon as possible

**Comment by WhiteBlackGoose** [comment] 2021-01-27 06:54
I published preview 6, it should work now

**Comment by WhiteBlackGoose** [comment] 2021-01-27 15:02
@Ranodj if you still work on your project using AM, try to update AM to version 1.2.0-preview.6. It seems to be my bad that you couldn't run your app (I have no idea why I couldn't reproduce it). Now it should work fine.

**Comment by WhiteBlackGoose** [comment] 2022-12-04 19:14
Ok so no reaction, I'm closing it as fixed

**Closed by WhiteBlackGoose** 2022-12-04 19:14 UTC
